version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=daancovid19sn
      - POSTGRES_PASSWORD=daancovid19sn
    volumes:
      - db_daancovid19sn:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.2
    volumes:
      - ./tmp/es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
volumes:
  es-data:
  db_daancovid19sn:
    external: true
