module.exports = {
    UserController: require('./user'),
    BackOfficeUserController: require('./back-office-user'),
    LocationController: require('./location'),
    ZoneController: require('./zone'),
    ContactController: require('./contact'),
    BarrierGestureController: require('./barrier-gesture'),
    GreenNumberController: require('./green-number'),
    SymptomController: require('./symptom'),
    PrevalenceController: require('./prevalence'),
    DailyReportController: require('./daily-report'),
    SelfReportingController: require('./self-reporting'),
    ElasticCallController: require('./elastic-call'),
    RiskFactorController: require('./riskfactor'),
    PushNotificationController: require('./push-notification'),
    PushNotificationOsController: require('./push-notification-one-signal'),
    ScreeningController: require('./screening'),
};